version: '3.3'  # Change this to '3.3' or another supported version

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}  # Make sure to include your env variable
